# Generated by Django 5.2 on 2025-04-15 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DekanatWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути у форматі: '+380XXXXXXXXX'.", regex='^\\+380\\d{9}$')], verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Dekanat Worker',
                'verbose_name_plural': 'Dekanat Workers',
                'ordering': ['firstname'],
            },
        ),
        migrations.CreateModel(
            name='Documenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('documenttypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specialityid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.speciality'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('zalikbook', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phonenumber', models.CharField(max_length=13, unique=True)),
                ('contractnumber', models.CharField(max_length=8, unique=True)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('specialityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.speciality')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['zalikbook'],
            },
        ),
    ]
