# Generated by Django 5.2 on 2025-04-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name'], 'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
    ]
