# Generated by Django 5.2 on 2025-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requests'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('number', 'specialityid'), name='unique_course_speciality'),
        ),
    ]
