# Generated by Django 5.2 on 2025-04-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dekanatworkers_group_delete_speciality'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
    ]
