# Generated by Django 5.2 on 2025-04-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dekanatworkers_documenttype_document_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalikbook', models.IntegerField(max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phonenumber', models.IntegerField(max_length=10, unique=True)),
                ('contractnumber', models.CharField(max_length=8, unique=True)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('specialityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.speciality')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Documents',
                'ordering': ['zalikbook'],
            },
        ),
    ]
