# Generated by Django 5.2 on 2025-04-15 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути у форматі: '+380XXXXXXXXX'.", regex='^\\+380\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
