# Generated by Django 5.2 on 2025-04-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_group_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dekanatworkers',
            table='dekanatworkers',
        ),
    ]
